CoolEvents/CoolEvents/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoolEvents.Models;
using System.Drawing;

namespace CoolEvents.Controllers
{
    public class EventsController : Controller
    {
        private readonly CoolEventsDBContext _context;

        public EventsController(CoolEventsDBContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            if(HttpContext.Session.GetString("IsAuthenticated") != "true")
            {
                return RedirectToAction("Login","Users");
            }

              return _context.Events != null ? 
                          View(await _context.Events.ToListAsync()) :
                          Problem("Entity set 'CoolEventsDBContext.Events'  is null.");
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ImageFile,Date")] Event @event)
        {
            if (!@event.IsValidImage())
            {
                ModelState.AddModelError(nameof(@event.ImageFile), "The file must be a valid image type (JPEG, PNG or GIF) and less than 2MB in size.");
            }

            if (ModelState.IsValid)
            {
                byte[] imageData = null;
                if (@event.ImageFile != null)
                {
                    using var stream = new MemoryStream();
                    await @event.ImageFile.CopyToAsync(stream);
                    imageData = stream.ToArray();
                }

                @event.Image = imageData;

                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(@event);
        }


        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ImageFile,Date")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (!@event.IsValidImage())
            {
                ModelState.AddModelError(nameof(@event.ImageFile), "The file must be a valid image type (JPEG, PNG or GIF) and less than 2MB in size.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var eventToUpdate = await _context.Events.FindAsync(id);

                    if (eventToUpdate == null)
                    {
                        return NotFound();
                    }

                    if (@event.ImageFile != null)
                    {
                        using var stream = new MemoryStream();
                        await @event.ImageFile.CopyToAsync(stream);
                        eventToUpdate.Image = stream.ToArray();
                    }

                    eventToUpdate.Name = @event.Name;
                    eventToUpdate.Description = @event.Description;
                    eventToUpdate.Date = @event.Date;

                    _context.Update(eventToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(@event);
        }


        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Events == null)
            {
                return Problem("Entity set 'CoolEventsDBContext.Events'  is null.");
            }
            var @event = await _context.Events.FindAsync(id);
            if (@event != null)
            {
                _context.Events.Remove(@event);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return (_context.Events?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public IActionResult GetImage(int id)
        {
            var eventItem = _context.Events.Find(id);
            if (eventItem != null && eventItem.Image != null)
            {
                return File(eventItem.Image, "image/jpeg");
            }
            else
            {
                return NotFound();
            }
        }

    }
}

CoolEvents/CoolEvents/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoolEvents.Models;

namespace CoolEvents.Controllers
{
    public class TicketsController : Controller
    {
        private readonly CoolEventsDBContext _context;

        public TicketsController(CoolEventsDBContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            if(HttpContext.Session.GetString("IsAdmin") == "true")
            {
                var coolEventsDBContext = _context.Tickets.Include(t => t.Event).Include(t => t.User);
                return View(await coolEventsDBContext.ToListAsync());
            }
            else if(HttpContext.Session.GetString("IsAuthenticated") == "true")
            {
                var coolEventsDBContext = _context.Tickets.Include(t => t.Event).Include(t => t.User).Where(x=>x.UserId == int.Parse(HttpContext.Session.GetString("UserId")));
                return View(await coolEventsDBContext.ToListAsync());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Event)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(string eventId)
        {
            try
            {
                Ticket ticket = new Ticket();
                ticket.EventId = int.Parse(eventId);
                ticket.UserId = int.Parse(HttpContext.Session.GetString("UserId"));

                _context.Tickets.Add(ticket);
                await _context.SaveChangesAsync();

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Description", ticket.EventId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "FirstName", ticket.UserId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,EventId")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Description", ticket.EventId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "FirstName", ticket.UserId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Event)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tickets == null)
            {
                return Problem("Entity set 'CoolEventsDBContext.Tickets'  is null.");
            }
            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket != null)
            {
                _context.Tickets.Remove(ticket);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
          return (_context.Tickets?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CoolEvents/CoolEvents/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var session = HttpContextAccessor.HttpContext?.Session;
    var controller = ViewContext.RouteData.Values["controller"].ToString();
    var action = ViewContext.RouteData.Values["action"].ToString();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoolEvents</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoolEvents.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoolEvents</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
                @if (session != null)
                {
                    @if (session.GetString("IsAuthenticated") == "true")
                    {
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                            <ul class="navbar-nav d-sm-inline-flex flex-grow-1 justify-content-end">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                                </li>
                                @if (session.GetString("IsAdmin") == "true")
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users Control</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Manage Tickets</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    }
                    else
                    {
                        // Get the current controller and action
                        string controllerName = ViewContext.RouteData.Values["controller"].ToString();
                        string actionName = ViewContext.RouteData.Values["action"].ToString();
                        // Check if the user is not on the Login page or the Register page
                        if (actionName == "Register")
                        {
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                                <ul class="navbar-nav d-sm-inline-flex flex-grow-1 justify-content-end">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                                    </li>
                                </ul>
                            </div>
                        }
                        else if(actionName == "Login")
                        {
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                                <ul class="navbar-nav d-sm-inline-flex flex-grow-1 justify-content-end">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
                                    </li>
                                </ul>
                            </div>
                        }
                    }
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CoolEvents - <a asp-area="" asp-controller="Home" asp-action="Home">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>